ClientParms:
  dealTypeExclusions: "CB"
  prismaBridgeUserId: "[prisma]331030953"
  useOrganisationIdForTenant: false
  retrieveAgencyIdFromMdm: false
  readOnlyEnvironment: false
  deploySnapshotJob: true
  airTimeHoursWeekdays: 8-23
  airTimeHoursWeekend: 11-17

intValue: 1
stringValue: "somestring"
